### ISSUE TITLE
Increase guess count to 6

### ISSUE THREAD

**Issue by HelloChrisLowe** [ChristianLowe/Discordle#2]

**Comment by timbslr** [comment]
Where do I find the guess count?

**Comment by HelloChrisLowe** [comment]
Hi @CodingFactoryT 

The Game class stores the current state of the game (current number of guesses), as well as has the check if there are currently 5 guesses. Currently it will return the game as over if there are 5 guesses, but we want to increase that to 6.

One more change has to be made for this. WordGraphicBuilder takes as part of it's constructor that maximum amount of words allowed. We also need to increase this value to 6 so that the rendered graphic has enough slots to fit all of the allowable words.
