### ISSUE TITLE
Limit the number of games played in a day for a player or introduce a cooldown

### ISSUE THREAD

**Issue by MrShadov** [ChristianLowe/Discordle#23]
Limit the times a player can play in a given day to 1 to allow more players to participate in either the am or pm game. This or introduce a cooldown mechanic that makes players who've played in a previous game unable to submit a guess until their cooldown time has elapsed after the start of the next game (ex w/ 1hr cd: player1 plays the am game -> 12pm a new game starts -> player1 tries submitting a word between 12pm-1pm -> error is returned: 'player1 is on cooldown between 12pm-1pm, player1 can submit a word after 1pm'). A cooldown would give time for other players to jump in after a game starts, but won't completely stop a game from being played by more 'active' players if other players are not participating on a given day.

**Comment by HelloChrisLowe** [comment]
This should be mostly resolved with the personalized cooldown feature added recently.
